### ISSUE TITLE
[AirQuality] Add SO2 Values

### ISSUE THREAD

**Issue by smf007** [kubawolanin/openhab2-addons#14]
Hello,

I notice that SO2 levels are available on some stations, example [Toronto-West](http://aqicn.org/city/canada/ontario/toronto-west/).  Would be nice to have this included.

Thanks!

**Comment by kubawolanin** [comment]
Hey @smf007,
Please reopen this issue in main [openhab2-addons](https://github.com/openhab/openhab2-addons/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+AirQuality) repository.
Cheers!

**Comment by kubawolanin** [comment]
BTW. If anyone's willing to do it, here's a list of files you need to modify in order to add a new channel:

* [AirQualityBindingConstants.java](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/AirQualityBindingConstants.java)
* [AirQualityHandler.java](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/handler/AirQualityHandler.java#L297)
* [AirQualityJsonIaqi.java](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/json/AirQualityJsonIaqi.java#L28)
* [README](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.airquality/README.md)
* [thing-types.xml](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.airquality/ESH-INF/thing/thing-types.xml#L19)
